FROM node:18.20.4-slim AS build
WORKDIR /app

COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build

RUN npm install -g @quasar/cli

EXPOSE 9005
CMD [ "quasar", "serve", "--history", "--port", "9005", "./dist/spa" ]
